# API - Application Programming Interface
* packaged programs generally meant to abstract away some complex interaction
* actually any class (so import) in Python is an API
* when we say "abstract" we mean you don't need to know how something works, just what it does
* often examples of APIs deal with getting data - called "endpoints"

### Installing third party modules
* Python has a built-in "package manager" called pip - connects to PyPi and handles installation
* Anaconda also has a package manager - conda
    * in fact it's probably time to upadte your Anaconda install: 
    
    `conda update --all`
* you can use either, pip probably has access to more packages, conda *may* be slightly better for Anaconda enviromnments
* install pandas_datareader:

    `pip install pandas-datareader`

In [1]:
# !pip install pandas-datareader

In [1]:
import pandas_datareader as pdr

In [2]:
data = pdr.get_data_yahoo('AAPL', start='20210321')

In [3]:
data.head()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-03-22,123.870003,120.260002,120.330002,123.389999,111912300.0,122.660973
2021-03-23,124.239998,122.139999,123.330002,122.540001,95467100.0,121.815987
2021-03-24,122.900002,120.070000,122.820000,120.089996,88530500.0,119.380455
2021-03-25,121.660004,119.000000,119.540001,120.589996,98844700.0,119.877502
2021-03-26,121.480003,118.919998,120.349998,121.209999,94071200.0,120.493835

In [4]:
data.describe()

,High,Low,Open,Close,Volume,Adj Close
count,253.000000,253.000000,253.000000,253.000000,2.530000e+02,253.000000
mean,150.462807,147.399288,148.836285,149.019486,8.677732e+07,148.624060
std,16.799521,16.049374,16.458094,16.423405,2.598390e+07,16.607903
min,120.400002,118.860001,119.540001,119.900002,9.797114e+06,119.191582
25%,135.119995,133.279999,134.449997,134.389999,6.884710e+07,133.595963
50%,149.429993,146.830002,148.429993,148.479996,8.328130e+07,147.933090
75%,164.479996,159.639999,161.679993,161.940002,9.931040e+07,161.733948
max,182.940002,179.119995,182.630005,182.009995,1.954327e+08,181.778397

In [5]:
data.pct_change()

                High       Low      Open     Close    Volume  Adj Close
Date
2021-03-22       NaN       NaN       NaN       NaN       NaN        NaN
2021-03-23  0.002987  0.015633  0.024931 -0.006889 -0.146947  -0.006889
2021-03-24 -0.010786 -0.016948 -0.004135 -0.019994 -0.072660  -0.019994
2021-03-25 -0.010089 -0.008911 -0.026706  0.004164  0.116504   0.004164
2021-03-26 -0.001480 -0.000672  0.006776  0.005141 -0.048293   0.005141
...              ...       ...       ...       ...       ...        ...
2022-03-15  0.009408  0.001865 -0.003632  0.029677 -0.145015   0.029677
2022-03-16  0.028476  0.027131  0.040756  0.029015  0.100425   0.029015
2022-03-17  0.006250  0.020523  0.009933  0.006454 -0.260848   0.006454
2022-03-18  0.021615  0.013513  0.011979  0.020919  0.631297   0.020919
2022-03-21  0.006749  0.023660  0.018690  0.007379 -0.920575   0.007379

[253 rows x 6 columns]

In [6]:
close = data['Adj Close']

In [10]:
[e / b - 1 for e,b in zip(close[1:], close)]

[-0.006888792286871448,
 -0.01999353027072337,
 0.00416355779717259,
 0.005141356762197846,
 0.0014850537263488839,
 -0.01227446322655712,
 0.01876566752731712,
 0.006958661143367184,
 0.023577174999416695,
 0.0024623175740456915,
 0.01339038703711437,
 0.01923377413582661,
 0.02025163444406286,
 -0.013233097770759317,
 0.02430653954028994,
 -0.01785314852754938,
 0.01870781159864099,
 -0.00252770010788006,
 0.00506843995706352,
 -0.012829975700829443,
 0.002929904502502634,
 -0.011685380959723046,
 0.018038605442632027,
 0.0029780182031649005,
 -0.002449741057322874,
 -0.006027175399712981,
 -0.0007487439062576762,
 -0.015133176994314268,
 0.00821534574275562,
 -0.0353855089046442,
 0.0019554528921943426,
 0.012802496177608313,
 0.005327360121451852,
 -0.025804498841002887,
 -0.007410281099872296,
 -0.024938548288312323,
 0.017919714944091947,
 0.01984477172568644,
 -0.009258515051098537,
 -0.011245753421548876,
 -0.0012815364248944805,
 0.021012079031357267,
 -0.014767072932940772,
 0.0133141652747224,
 -0.0015735774974560135,
 -0.00039395401044273193,
 -0.012376782717804069,
 -0.005348102132856081,
 -0.0026483096766292125,
 0.0062762289139921545,
 -0.012154183136324326,
 0.019022216400782277,
 7.942292580187527e-05,
 0.006671969627677354,
 0.0030770830430362217,
 -0.008023207081886863,
 0.009832598793492409,
 0.024578048536902042,
 -0.006437775548783997,
 0.00393393327726721,
 0.012600787165081284,
 -0.010091573298520062,
 0.01410365750740361,
 0.012698428876938062,
 -0.002089790540586889,
 -0.002168893094337876,
 -0.0022488406048793985,
 0.012546097849755133,
 0.011500091692854708,
 0.004621201732754043,
 0.0022634984773886035,
 0.01959642404443329,
 0.014718548743539506,
 0.017955151341994213,
 -0.00919979407622551,
 0.01305499508278074,
 -0.004203679951779282,
 0.00788929786776027,
 0.024100346934562644,
 -0.0044920375057341255,
 -0.014075945625684594,
 -0.026914280151528303,
 0.025973813626608333,
 -0.0051315484174484505,
 0.009628586520168625,
 0.011989035172645046,
 0.0028946018558335673,
 -0.014900330206522594,
 -0.012196013209259005,
 0.004552327028536807,
 0.0015106709681194097,
 -0.0023310848574139564,
 0.01264437472325497,
 -0.0027823667597588475,
 0.0007484976865186344,
 -0.004767087900099387,
 -0.0003421522338730165,
 -0.0033539881919171233,
 0.0017857270461618668,
 0.020773302856759157,
 0.0014104354962374277,
 0.013547893729985327,
 -0.006153926840348767,
 -0.025501115423570586,
 0.0023230960089311026,
 0.010156754786368793,
 0.010257207659411627,
 -0.0006013512415542488,
 -0.00842132432713516,
 -0.005527001421249511,
 0.007184527738557378,
 0.03041705570091846,
 -0.008424684014394446,
 0.004478702255636291,
 0.007474896239126005,
 0.00423047405148913,
 0.015489329295501397,
 -0.010083661236634844,
 -0.006704868499408989,
 -0.03310195014930106,
 0.0038934848219518425,
 -0.00956213891446367,
 0.006143763614056885,
 -0.001610544027542793,
 -0.01834788420998512,
 -0.021361133098039442,
 0.0034280077168440393,
 0.01687239830743703,
 0.006719223830511378,
 0.0006129381212811591,
 -0.010549886938345798,
 -0.02380133417815844,
 0.006482912273241492,
 -0.009311757978492041,
 0.008127121326264808,
 -0.02460558904248289,
 0.01415843138910855,
 0.006307143853147901,
 0.00908441861121645,
 -0.002721826162761176,
 -0.0006296879955406398,
 -0.009103069373070483,
 -0.004239947235827768,
 0.02022566731737263,
 0.00751254236754173,
 0.011806146831827347,
 0.01508012914042145,
 0.003361158709555223,
 0.0014739802356051879,
 -0.005284966689519832,
 -0.0003362843623860856,
 0.004574820545116376,
 -0.003147613094226176,
 0.02499161477661893,
 -0.018155649190818024,
 -0.00560746976256199,
 0.00711603954635831,
 0.009798681086816696,
 -0.0034986485157104674,
 0.0035823872026932158,
 -0.005552598142273157,
 0.0024594048904347243,
 -0.019163181340561608,
 -0.00033805871872338855,
 0.014336966446270472,
 6.661752181402747e-05,
 0.006666706729581806,
 0.016490066519995628,
 0.028536018309588185,
 0.01697609107439524,
 0.002927367652044932,
 0.00242210517536523,
 0.0032835745736796706,
 -0.03167840884518325,
 0.021873560449993112,
 0.03157770987877151,
 -0.0032063022092799764,
 -0.006129836479277451,
 -0.0117244742487278,
 0.021502806138102626,
 0.035446285640035935,
 0.022783110263252748,
 -0.0029701269075643744,
 0.028013356548261203,
 -0.0206742667024592,
 -0.008023200235215522,
 0.02850910672885343,
 -0.03926385689829104,
 -0.006501718069199192,
 -0.008122082995582813,
 0.019086942355844627,
 0.015318767775768238,
 0.003643845702054005,
 0.02297480686837372,
 -0.005767228845311334,
 0.0005020026420115009,
 -0.006578207152797333,
 -0.0035353411945054924,
 0.025004172969140592,
 -0.01269156651931258,
 -0.026599933309720214,
 -0.016693292060333764,
 0.0009883770869549835,
 0.00011615962266664503,
 0.01678378142167647,
 0.0025701947293599314,
 -0.019028024972982616,
 0.0051106959584428235,
 -0.018894172998240477,
 -0.021024751722017565,
 -0.01034715671706743,
 -0.012765044938485848,
 -0.004864367503816247,
 -0.011384654651673931,
 -0.0005632998528019018,
 -0.0029431330101519215,
 0.06977761550430284,
 0.026125745758885266,
 -0.0009726562694633012,
 0.007044295579192061,
 -0.016719773516582936,
 -0.0016793681864307741,
 -0.004234559603942367,
 0.018466725511581794,
 0.008293753549481586,
 -0.02359884099680365,
 -0.020218427993619836,
 0.0014231824835904128,
 0.023152465006342826,
 -0.0013889128057177347,
 -0.021269186346200564,
 -0.009355766137921773,
 -0.017812287347162448,
 -0.02586416632525068,
 0.01668019020913314,
 0.012965469700934706,
 0.0016377858882354879,
 -0.011627896231359958,
 0.02058823941900667,
 -0.001981279033932526,
 -0.01840821534766368,
 -0.02371756548762427,
 -0.011676086470301161,
 0.034997423916368176,
 -0.027186209013482565,
 -0.02390870831928371,
 -0.026562403695717718,
 0.029677342754030223,
 0.02901541109199557,
 0.006454030972694147,
 0.020918943546848645,
 0.007378989787740098]